# Задаёт параметры по умолчанию для всего сервера Prometheus
global:
  # Интервал сбора данных
  # scrape - процесс, когда Prometheus обращается к приложениям по HTTP и забирает у них метрики
  scrape_interval: 15s

# блок содержит список заданий, определяющие откуда Prometheus будет собирать метрики
scrape_configs:
  # Prometheus добавляет к каждой собранной метрике этот лейбл.
  # Это позволяет фильтровать метрики по тому, от какого приложения они пришли.
  - job_name: 'prometheus'
    # Указывает, что список целей для этого задания будет задан статически
    static_configs:
      # Список целей
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    static_configs:
      # Это имя хоста или сервиса, а не IP-адрес.
      # Так как Prometheus чаще всего запускается в Docker или Kubernetes, он использует внутреннюю DNS.
      - targets: ['node_exporter:9100']
