# отключает аутентификацию
auth_enabled: false


# Настройки HTTP-сервера
server:
  # порт, на котором Loki будет принимать HTTP-запросы.
  http_listen_port: 3100
# Общие настройки
common:
  # базовый путь в файловой системе, где Loki будет хранить все свои данные
  path_prefix: /tmp/loki
  # настройки хранилища
  storage:
    # указывает, что Loki будет хранить данные в файловой системе
    filesystem:
      # директория для хранения "чанков" (сжатые куски логов)
      chunks_directory: /tmp/loki/chunks
      # директория для хранения правил записи
      rules_directory: /tmp/loki/rules
  # фактор репликации
  replication_factor: 1
# Схема хранения данных
schema_config:
  # список конфигураций схем
  configs:
    #  говорит Loki, что эта конфигурация применима для данных начиная с этой даты
    - from: 2020-10-24
      # тип хранилища для индексов(boltdb — это встроенная база данных ключ-значение)
      # boltdb-shipper — особый режим, который позволяет хранить индексы тоже в файловой системе
      store: boltdb-shipper
      # где хранить сами чанки (данные логов)
      object_store: filesystem
      # версия внутренней схемы данных
      schema: v11
      # настройки для индексов
      index:
        # префикс для файлов индексов. Файлы будут называться типа index_174330, index_174331
        prefix: index_
        # период ротации индекса, каждые 24 часа Loki создает новый файл индекса
        period: 24h